app/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('create/', views.Create.as_view(), name='create'),
    path('delete/', views.Delete.as_view(), name='delete'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('settings/', views.Settings.as_view(), name='settings'),
    path('uploadUserImage/', views.UploadUserImage.as_view(), name='uploadUserImage'),
    path('deleteUserImage/', views.DeleteUserImage.as_view(), name='deleteUserImage'),
]

app/src/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_delete
from django.dispatch.dispatcher import receiver
from django.core.files.storage import FileSystemStorage


class UserImage(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    src = models.URLField(default="/static/images/user-default.jpg")

    def __str__(self):
        return self.user.username


@receiver(post_delete, sender=UserImage)
def userimage_delete(sender, instance, **kwargs):
    fs = FileSystemStorage()
    fs.delete(instance.src[7:])

app/accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    email = forms.EmailField(min_length=8, max_length=254)
    password = forms.CharField(min_length=8, max_length=24, widget=forms.PasswordInput())
    if email in [None, ''] or password in [None, '']:
        raise forms.ValidationError("Some fields are empty.")

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')

        if not email and not password:
            raise forms.ValidationError('Form is invalid.')


class CreateForm(forms.Form):
    username = forms.CharField(min_length=3, max_length=16)
    email = forms.EmailField(min_length=8, max_length=254)
    password = forms.CharField(min_length=8, max_length=24, widget=forms.PasswordInput())
    confirm_password = forms.CharField(min_length=8, max_length=24, widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super(CreateForm, self).clean()
        username = cleaned_data.get('username')
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if username in [None, ''] or email in [None, ''] or password in [None, ''] or confirm_password in [None, '']:
            raise forms.ValidationError("Some fields are empty.")
        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")
        try:
            match = User.objects.get(username=username)
            raise forms.ValidationError('This username is already in use.')
        except User.DoesNotExist:
            # OK, no matches
            pass        
        try:
            match = User.objects.get(email=email)
            raise forms.ValidationError('This email address is already in use.')
        except User.DoesNotExist:
            # OK, no matches
            pass        

app/accounts/views.py
import uuid
import os
import traceback

from django.views import generic
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.files.storage import FileSystemStorage

# from src.utils.images import check_image, process_user_image
# from src.settings import userimage as settings_userimage
from accounts.models import UserImage, userimage_delete 
from .forms import LoginForm, CreateForm


class Logout(generic.View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
        return redirect('accounts:login')


class Login(generic.View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('accounts:settings')
        return render(request, 'accounts/login.html', {'form': LoginForm()})
    
    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = None
            try:
                user = authenticate(request,
                                    username=User.objects.get(email=form.cleaned_data['email']).username,
                                    password=form.cleaned_data['password'])
                login(request, user)
                return redirect('accounts:settings')
            except:
                form.add_error(None, 'Incorrect username or password.')
        else:
            form.add_error(None, 'Form is invalid.')
        return render(request, 'accounts/login.html', {'form': form})


class Create(generic.View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('accounts:settings')
        return render(request, 'accounts/create.html', {'form': CreateForm()})

    def post(self, request):
        form = CreateForm(request.POST)
        if form.is_valid():
            try:
                user = User()
                user.username = form.cleaned_data['username']
                user.email = form.cleaned_data['email']
                user.set_password(form.cleaned_data['password'])
                user.save()
                user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password'])
                if user is not None and user.is_active:
                    login(request, user)
                    return redirect('accounts:settings')
            except:
                form.add_error(None, 'Internal Server Error.')
        return render(request, 'accounts/create.html', {'form': form})


class Delete(generic.View):
    def get(self, request):
        if request.user.is_authenticated:
            if request.user.is_superuser or request.user.is_staff:
                messages.error(request, "This action is not allowed.")
                return redirect('accounts:settings')
            try:
                request.user.delete()
                messages.success(request, "Your account was succesfully deleted.")
                return redirect('accounts:login')
            except User.DoesNotExist:
                messages.error(request, "User does not exist")
            except Exception as e: 
                messages.error(request, e.message)
            return redirect('accounts:settings')
        return redirect('accounts:login')
        

class Settings(generic.View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        userimage = ''
        try:            
            userimage = request.user.userimage.src
        except:
            userimage = '/static/images/user-default.jpg'
        finally:
            return render(request, 'accounts/settings.html', {'userimage': userimage})


class UploadUserImage(generic.View):
    def post(self, request):
        if request.user.is_authenticated:
            try:
                if request.FILES["image_file"]:
                    print()
                    image_file = request.FILES["image_file"]
                    fs = FileSystemStorage()
                    #TODO CHECK IMAGE
                    #TODO PROCESS IMAGE
                    #TODO USE TRY
                    filename = fs.save("users/userimage-" + str(uuid.uuid4()) + ".jpg",
                                    image_file)
                    image_url = fs.url(filename)

                    if UserImage.objects.filter(user=request.user).exists():
                        userimage = UserImage.objects.get(user=request.user)
                        userimage.src = image_url
                        userimage.save()
                    else:
                        # Create new blank model
                        userimage = UserImage(user=request.user)
                        userimage.save()
                        # Save new src in model
                        userimage.src = image_url
                        userimage.save()
                    return render(request, 'accounts/settings.html', {'userimage': userimage.src})
            except:
                messages.error(request, "Unable to upload new user image.")
        return redirect('accounts:settings')


class DeleteUserImage(generic.View):
    def post(self, request):
        try:
            if request.user.is_authenticated:
                if UserImage.objects.filter(user=request.user).exists():
                    UserImage.objects.get(user=request.user).delete()
        except Exception as e:
            trace_back = traceback.format_exc()
            message = str(e)+ " " + str(trace_back)
            print (message)
            messages.error(request, "Unable to delete user image.")
        finally:
            return redirect('accounts:settings')

app/accounts/templates/accounts/create.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/create.css' %}">
{% endblock %}

{% block title %}
Create Account
{% endblock %}

{% block content %}

<div id="form-container">
  <form class="ui form" id="create-form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h2 class="ui dividing header">Create Account</h2>
    {% if form.errors.values %}
    <div class="ui negative message">
      {% for error in form.errors.values %}
      {{ error }}
      {% endfor %}
    </div>
    {% endif %}

    {{ form.source.errors }}
    {{ form.source }}

    {% for field in form.visible_fields %}
    <div class="field">
      {{ field.label }}:
      {{ field }}
    </div>
    {% endfor %}

    <div class="field">
      <div class="ui checkbox">
        <input type="checkbox" tabindex="0" class="hidden" required>
        <label>I agree to the 
          <a href="#">Terms and Conditions</a>
        </label>
      </div>
    </div>

    <button class="ui fluid primary button" type="submit" id="create-btn">Create Account</button>
    <div class="ui horizontal divider">
      Already have an account?
    </div>
    <a href="{% url 'accounts:login' %}" class="ui fluid primary button">
      Log In
    </a>
  </form>
</div>

{% endblock %}

{% block js %}
<script type="module" src="{% static 'accounts/js/create.js' %}"></script>
{% endblock %}

app/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/login.css' %}">
{% endblock %}

{% block title %}
Login
{% endblock %}

{% block content %}


<div id="form-container">
<form class="ui form" id="login-form" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <h2 class="ui dividing header">Log in to your account</h2>
  {% if form.errors.values %}
  <div class="ui negative message">
      {% for error in form.errors.values %}
        {{ error }}
      {% endfor %}
  </div>
  {% endif %}  

  {{ form.source.errors }}
  {{ form.source }}

  {% for field in form.visible_fields %}
  <div class="field">
      {{ field.label }}:
      {{ field }}
  </div>
  {% endfor %}

  <div class="ui field">
    <a href="#">Forgot your password?</a>
  </div>


  <button class="ui fluid primary button" type="submit" id="login-btn">Log In</button>
  
  
  <div class="ui horizontal divider">
    New to us?
  </div>
  <a href="{% url 'accounts:create' %}" class="ui fluid primary button">
    Create Account
  </a>
</form>
</div>

{% endblock %}

{% block js %}
<script type="module" src="{% static 'accounts/js/login.js' %}"></script>
{% endblock %}

app/accounts/templates/accounts/settings.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/settings.css' %}">
{% endblock %}

{% block title %}
Settings
{% endblock %}

{% block content %}

<div class="ui container stackable center aligned grid">

    <div id="settings-container" class="ui center aligned grid">

        <div class="row" id="image-uploder">
            <form action="{% url "accounts:uploadUserImage" %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="image_file">
                <input type="submit" value="submit" />
            </form>

            {% if userimage %}
                <p>Source: <a href="{{ userimage }}">{{ userimage }}</a></p>
                <img src="{{ userimage }}"></img>
            {% endif %}

            <form action="{% url "accounts:deleteUserImage" %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="submit" value="Delete image" />
            </form>
        </div>



        <div class="row">
            Account settings:
            <a href="{% url 'accounts:delete' %}">Delete Account</a>
        </div>

    </div>

</div>

{% endblock %}

{% block js %}
<script type="module" src="{% static 'accounts/js/settings.js' %}"></script>
{% endblock %}