app/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('create/', views.Create.as_view(), name='create'),
    path('delete/', views.Delete.as_view(), name='delete'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('settings/', views.Settings.as_view(), name='settings'),
    path('uploadUserImage/', views.UploadUserImage.as_view(), name='uploadUserImage'),
    path('deleteUserImage/', views.DeleteUserImage.as_view(), name='deleteUserImage'),
]

app/src/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/base.html
{% load static %}
{% load compress %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href={% static "dist/semantic.min.css" %}>
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    
    <title>{% block title %}{% endblock %} - {{ PROJECT_NAME }}</title>
    <meta name="description" content="Project general description.">
    
    {% block page_meta %}
    {% endblock %}

    {% block css %}
    {% endblock %}
</head>

<body>
    <header>
        {% include "header.html" %}
    </header>

    {% if messages %}
    <div id="messages-container">
        {% for message in messages %}
        <div class="ui {{ message.tags }} message">
            <i class="close icon"></i>
            <div class="header">
            
            </div>
            <p>{{ message }}</p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    
    <content>
        {% block content %}
        {% endblock %}
    </content>

    <footer class="ui vertical footer segment">
        {% include "footer.html" %}
    </footer>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="{% static "dist/semantic.min.js" %}"></script>
    <script type="module" src="{% static "js/base.js" %}"></script>

    {% block js %}
    {% endblock %}
</body>

</html>

app/templates/footer.html
{% load static %}
<link rel="stylesheet" href="{% static "css/footer.css" %}">

<div class="ui center aligned container">
    <img src="{% static "images/logo.png" %}" class="ui centered mini image" alt="Logo">
    <div class="ui horizontal small divided link list">
        <a class="item" href="#">Site Map</a>
        <a class="item" href="#">Contact Us</a>
        <a class="item" href="#">Terms and Conditions</a>
        <a class="item" href="#">Privacy Policy</a>
    </div>
</div>

<script type="module" src="{% static "js/footer.js" %}"></script>

app/templates/header.html
{% load static %}
<link rel="stylesheet" href="{% static "css/header.css" %}">

<div class="ui fixed inverted menu">
    <div class="ui container">
        <a href="#" class="header item">
            <img class="logo" src="{% static "images/logo.png" %}" alt="Logo">
            {{ PROJECT_NAME }}
        </a>
        <a href="#" class="item">Link</a>

        <div class="right menu">
            {% if request.user.is_authenticated %}
            <div class="ui simple dropdown item">
                {% if request.user.userimage.src %}
                <img class="ui avatar image" src="{{ request.user.userimage.src }}">
                {% else %}
                <img class="ui avatar image" src="{% static "images/user-default.jpg" %}">
                {% endif %}
                <span id="menu-username">{{ request.user.username }}</span> <i class="dropdown icon"></i>
                <div class="menu">
                    <a class="item" href="{% url 'accounts:settings' %}">
                        <i class="cog icon"></i>Account Settings
                    </a>
                    <a href="{% url 'accounts:logout' %}" class="ui item">
                        <i class="sign-out icon"></i>Log Out
                    </a>
                </div>
            </div>
            {% else %}
            <a class="item" href="{% url 'accounts:login' %}">Log In</a>
            <a class="item" href="{% url 'accounts:create' %}">Create Account</a>
            {% endif %}
        </div>
    </div>
</div>

<script type="module" src="{% static "js/header.js" %}"></script>